# URL usando el puerto 6543 (Session Pooler compatible con IPv4)
spring.datasource.url=jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.rwvexmumjnnhptmrixxm
spring.datasource.password=CRMPROJRCT1501

# Driver y Dialecto de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true