# En local usará H2. En Railway usará las variables de entorno inyectadas.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:crmbandas;DB_CLOSE_DELAY=-1}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# Consola H2 para desarrollo local
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Asignación del puerto dinámico
server.port=${PORT:8080}